'database': dba,

File "C:\Users\lith\Desktop\DojoAssignments\Python\Flask\flask_mysql_friendsdb\mysqlconnection.py", line 9, in __init__
    'database': dba, # we got db as an argument
NameError: global name 'dba' is not defined

make sure the database exists, is named correctly in server.py
----------------------------------------------------------------------------


OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (10061)") (Background on this error at: http://sqlalche.me/e/e3q8)
Changed port to a different port- make sure mySQL is running on the port you think it is.

------------------------------
OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'rooty'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)

username is incorrect (rooty@localhost
correct username
---------------------------------------------
OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)

access denied- user name is correct but password is wrong - fix password.
